title: Daniel Limanowski
description: the red team is watching
show_downloads: false
theme: jekyll-theme-slate
disqus:
    shortname: b1tst0rm
url: "https://b1tst0rm.net"
#future: true # set true when posts are in progress and want them rendered
